### ISSUE TITLE
[S1]-Display markdown documentations

### ISSUE THREAD

**Issue by dusunax** [dusunax/blog#3]
# Display markdown documentations

## Todo
- [x] Convert markdown contents to JSON
  - https://contentlayer.dev/
- [x] Display type-safe markdown documentations
- [x] Get doucuments from remote source (github repository)
- [x] Display documents list in deployed environment 
  - has Issue: #2

## ScreenShot

<details>
<summary>🖼️ list page_240414</summary>

- list page: `/`
- will replace with `/docs` route, after implement main page
![image](https://github.com/dusunax/blog/assets/94776135/694ca0e4-15d2-416e-8285-b0479527e1ed)

</details>

<details>
<summary>🖼️ detail page_240414</summary>
    
- detail page: `/docs/[slug]`
![image](https://github.com/dusunax/blog/assets/94776135/d90d7728-cc57-4e3e-ade7-a9b44724e1d7)

</details>

**Comment by dusunax** [comment]
# Display markdown documentations
> completed at 29.4.2024

## Works
- use github sub module #2 
- remove cache when unifies case #4
- add some Mdx convert features for Quiz components & route - test for other study.

## Screenshot
![image](https://github.com/dusunax/blog/assets/94776135/0a9c216b-4d85-4c4a-95f7-167980d435cf)
![image](https://github.com/dusunax/blog/assets/94776135/d24ff392-f37b-4839-9211-562aee6b1246)
![image](https://github.com/dusunax/blog/assets/94776135/001ddb66-4316-41fe-9247-87ca019afb48)
