### ISSUE TITLE
feat: 버튼 박스, tag 박스, 장표 상세 페이지 추가_240506

### ISSUE THREAD

**Issue by dusunax** [dusunax/blog#7]
- 이전 작업 - #6 

### Todo
- [x] slide 상세 페이지 추가
- [x] 1번 타입의 슬라이드에도 page 수 추가
![image](https://github.com/dusunax/blog/assets/94776135/c0df0f6a-d42e-47bb-8005-5e301ef5096c)
- [x] 파일 다운로드 기능 추가
- [x] 작성날짜 표기
- [x] 날짜순 정렬 추가

---

# 버튼 박스, tag 박스, 장표 상세 페이지 추가_240506

- slide 상세 페이지 추가
- 파일 다운로드 button 추가
- 썸네일 태그 박스 정리
- item createdAt
  - attribute 추가, 리스트 정렬 추가

## Slide Item
- ThumbnailTagBox: 우측 상단
  - 각 아이템의 page 수, 파일 유형 추가
- SlideItemButtonBox: 우측 하단
  - 파일 다운로드 기능 추가 
![image](https://github.com/dusunax/blog/assets/94776135/f5350b17-4ddd-43dc-85cb-1c837ee1993d)

## Detail page - PDF
![image](https://github.com/dusunax/blog/assets/94776135/a8f33398-d454-409c-8599-fb770bc902ac)

## Detail page - png Images
![image](https://github.com/dusunax/blog/assets/94776135/02587e92-fe43-48ef-9ba5-6200582e9328)

### 최신순
![image](https://github.com/dusunax/blog/assets/94776135/25028a70-c8ee-4f4d-bc78-2eab5a332b5d)

### 오래된순
![image](https://github.com/dusunax/blog/assets/94776135/dd127e90-d405-4115-b19a-857de2270cc0)

**Comment by dusunax** [comment]
### 이미지 최적화 레퍼런스
- https://oliveyoung.tech/blog/2023-06-09/nextjs-image-optimization/
- https://fe-developers.kakaoent.com/2022/220714-next-image/
- https://velog.io/@pds0309/nextjs-최소한의-이미지-최적화하기
