### ISSUE TITLE
feat: Next.js와 이미지 최적화_240509

### ISSUE THREAD

**Issue by dusunax** [dusunax/blog#8]
- 이전 작업 - #7

## Todo

- [x] 이미지 최적화
  - [x] 로컬 이미지에 blur placeholder 추가
  - [x] AVIF 사용하도록 설정
- [x] 이미지 로딩 레이아웃 쉬프트 개선
  - [x] witdh, hight 조정
- [ ] ~페이지네이션~ => 추후 작업

---

# Next.js와 이미지 최적화_240509

- 주제: CLS, FCP 개선
- 문서읽기: 틈틈이
- 작업 시간: 8시반~11시반

## 이미지 최적화 레퍼런스
- [x] https://nextjs.org/docs/app/building-your-application/optimizing/images
- [x] https://www.youtube.com/watch?v=IU_qq_c_lKA
- [x] https://oliveyoung.tech/blog/2023-06-09/nextjs-image-optimization/
- [ ] https://fe-developers.kakaoent.com/2022/220714-next-image/
- [x] https://velog.io/@pds0309/nextjs-최소한의-이미지-최적화하기
- [ ] https://docs.google.com/presentation/d/12kpH3kBcj691NH0Z05Yj0Wa--JjMUTDaprf-R_7gN2g/edit#slide=id.g22cd1445457_0_0

## 1. 👀 next/image 문서 살펴보기
- next/image: https://nextjs.org/docs/app/building-your-application/optimizing/images
  - 장치 크기에 맞춘 이미지 크기
  - AVIF, WebP 이미지 형식
  - CLS 발생 방지 (width, height) 
  - 기본 레이지 로드
  - 이미지 리사이징
> Asset Flexibility: On-demand image resizing, even for images stored on remote servers 👈 이 부분 확인하기
> ![image](https://github.com/dusunax/blog/assets/94776135/9c50bad0-bab7-4a44-8a37-44752c1ad38d)
- 로더 Loader
  - 이미지의 URL을 생성하는 기능
  - srcset(크기별 url set) 자동 생성
  - 커스텀 로더 작성 가능
    - https://nextjs.org/docs/app/api-reference/components/image#loader
  - LCP element에 priority 지정할 수 있음 `<Image ... priority />`
  - 이미지 크기 조정
    > - Automatically, using a [static import](https://nextjs.org/docs/app/building-your-application/optimizing/images#local-images)
    > - Explicitly, by including a [width](https://nextjs.org/docs/app/api-reference/components/image#width) and [height](https://nextjs.org/docs/app/api-reference/components/image#height) property
    > - Implicitly, by using [fill](https://nextjs.org/docs/app/api-reference/components/image#fill) which causes the image to expand to fill its parent element.
  - fill 사용 시 부모 엘리먼트 사이즈이며 object-fit, object-position 설정 가능

## 2. 👀 Make Your Image Loading Blurry in Next.js
> https://medium.com/@Furki4_4/make-your-image-loading-blurry-in-next-js-0f0e5bf3dc7c

문서에 명시된 대로 동적 이미지에 대한 Image 구성 요소의 BlurDataUrl 속성에 [dataURL을](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs) 전달해야 합니다. dataURL은 기본적으로 base64 형식으로 흐린 이미지 데이터를 보유하는 문자열입니다.

- 라이브러리 사용: [sharp](https://www.npmjs.com/package/sharp), ~[plaiceholder](https://www.npmjs.com/package/plaiceholder):commonJS~

## 3. 👀 placeholder 문서
- 반환값 확인하기: https://plaiceholder.co/docs

**Comment by dusunax** [comment]
## Next Todo

- [ ] (next/image로 최적화 부족하면) S3에 썸네일 이미지 보관 // 람다 리사이징
  - 리소스 사이즈 조정
  - PDF 썸네일의 경우 > 리소스 다운로드 자체에 시간이 걸리기 때문에, 썸네일 이미지를 생성해서 외부에 저장하는 과정이 필요할 것으로 보입니다.
  - 해당 과정에서 deprecated된 react-pdf 라이브러리도 제거할 예정입니다.
